version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3009:3009"  # Maps port 3000 on the host to port 3000 on the container
    networks:
      - itpa_backend_default

  nginx:
    image: nginx:latest
    container_name: omnadata-nginx
    ports:
      - "80:80"
     # - "443:443"
    volumes:
      - /home/ubuntu/interns_devops/nginx/nginx.conf:/etc/nginx/nginx.conf
    #  - /etc/nginx/ssl:/etc/nginx/ssl:ro  # SSL certificate files
    networks:
      - itpa_backend_default

    depends_on:
      - react-app

networks:
  itpa_backend_default:
    driver: bridge







 #   volumes:
  #    - .:/app        # Mounts the current directory to /app in the container for live reloading
#    environment:
   #   - NODE_ENV=development  # Set environment variable for development mode
